---
title: "calibration"
author: "Xiaoliang Zhou"
date: '2022-11-25'
output: html_document
---

# install 'RaschKit' package (if not done yet)

```{r}
# 1. Create a project file 'xxx.Rproj' in a working directory.
# 2. Open 'xxx.Rproj'. From bottom right pane, 
# click 'Packages' (3rd button after 'Files', 'Plots').
# click 'Install'. From 'Install from', select 'Package Archive File...'.
# Click 'Browse'. Enter into 'File name' file path 'T:\Xiaoliang Zhou'.
# Select compressed file 'RaschKit_1.0.0.tar.gz'. 
# Click 'Open'. 
# Click 'Install'.
```

```{r}
library(RaschKit)
install_packages_ls()
create_folders() 
```

```{r}
# 1. move this xxx.Rmd file into the 'rCode' folder just created.
# 2. Put the three attached files into 'dataRaw' folder.
# 3. Open this .Rmd file via 'xxx.Rproj'.
# 4. Run code below. When done with running, calibrate 
# would output instructions on where to find key results and/or QA check files.
```

# ####### anchoring ######

```{r}
# Use received files such as codebook to create 
# an Excel file (anchors.xlsx) with a sheet named as calibrate's 'test' argument. 
# On that sheet are two columns 'Item' (item labels) and 'Delta' (anchor estimates).
# Put this anchors.xlsx file into 'data' folder.

# If use a newly-generated .anc file to do anchoring, copy that file from 'output'
# folder into 'input' folder and set 'anchor_read=TRUE' in calibrate. 

# Note that anchor logit difficulty estimates in Column 'Delta' would be used to 
# anchor current cycle's items onto previous cycles. Or, newly-generated .anc file 
# is used to produce equivalence table and ability estimates.

# Set 'anchor' argument as TRUE to do anchoring
calibrate(anchor=TRUE, test='FPA', pid='ID number', n_cov=1, keys=keys, 
    labels=labels)
```
