---
title: "calibrate"
author: "Xiaoliang Zhou"
date: '2022-11-25'
output: html_document
---

# install 'RaschKit' package (if not done yet)

```{r}
# 1. Create a project file 'xxx.Rproj' in a working directory.
# 2. Open 'xxx.Rproj'. From bottom right pane,    
#    click 'Packages' (3rd button after 'Files', 'Plots').
#    click 'Install'. From 'Install from', select 'Package Archive File...'.
#    Click 'Browse'. Enter into 'File name' file path 'T:\Xiaoliang Zhou'.
#    Select compressed file 'RaschKit_1.0.0.tar.gz'. 
#    Click 'Open'. 
#    Click 'Install'.
```

```{r}
library(RaschKit)
install_packages_ls()
create_folders() 
```

```{r}
# 1. move this .Rmd file into the 'rCode' folder just created.
# 2. Put received files into 'dataRaw' folder.
# 3. Open this .Rmd file via 'xxx.Rproj'.
# 4. Run code below chunk by chunk. Note that when done with running calibrate 
#    would output instructions on where to find key results and QA check files.
```

# clean data

```{r}
# read data: Used for 'data' argument of Function 'calibrate' (Chunk 'calibrate' below)
# Note that data should have covariate columns first in data and response columns after
resp <- readxl::read_xlsx(list.files(here::here('dataRaw'),
         'data', # revised to file name
         full.names = TRUE)) %>% 
    map_df(~toupper(.x))

# Check whether columns have responses other than valid ones like A,B,C,D....
# If there is invalid one, put that into 'missCode2Conv' argument of Function 'calibrate' to recode them.
# If default of 'missCode2Conv' includes non-response symbol found in items, can ignore missCode2Conv below.
lapply(resp[-1], table)

# read codebook
cd <- readxl::read_xlsx(list.files(here::here('dataRaw'),
         'codebook', # revised to file name
         full.names = TRUE)) %>% 
    # row_to_names(1) 
keys <- cd %>% pull(Key) # Used as 'keys' for'calibrate' (below)
labels <- cd %>% pull(Item) # Used as 'labels' for'calibrate' (below)

# Update keys changed during the scaling process.
# This may occur when you send 1st round of item analysis results to test developers
# and they advise psychometricians to change key, use double key, or remove item.
keys[25] <- 'A' 
keys[53] <- 'B'
keys[67] <- 'C'
```

# calibrate (one test) 

```{r}
# Run '?calibrate' to know the meaning of the arguments.
calibrate(test='FPA', data=resp, pid='ID number', n_cov=1, keys=keys, labels=labels)
```

# ##### useful arguments in 'calibrate' ###### 

# Must set 

```{r}
# test: Test name, e.g., 'GAT'; any meaningful name; 'xxx' below
# pid: Candidate ID variable name in data
# n_cov: Number of covariates before responses
```

# May ignore

```{r}
# data: ignore if 'xxx.xlsx' (or xxx.sav) in 'data' folder
# keys: ignore if correct answers all coded as 1 (usually in codebook)
# labels: ignore if column names same as labels (usually in codebook)
```

# Set if test developer advises so 

```{r}
# delete: int Vector of item order, or char vector of item labels
# dbl_key: list(`5`=c(1,3), `29`=c(3,4))
```

# Regressor

```{r}
# regr_vec_char: categorical vector of regressor names in data
```

# Multi-dimensional modeling

```{r}
# n_dims: integer Vector of dimensions' item numbers in test
# dim_names: dimension names (e.g., c('Literacy', 'Numeracy')); any meaningful name
```

# Polytomous items

```{r}
# Prepare key file:
# In 'data' folder, add 'keys.xlsx' file (No need if already there);
# In 'keys.xlsx', add a sheet named as 'test' argument of 'calibrate'
# In the sheet, add three columns (row order same as response order in data):
#   Item: item labels; same as 'labels' argument of 'calibrate'
#   Key: key for MC items; maximum score for polytomous items
#   Max_score: maximum score for each item
#   Key2: 2nd key; ignore if no double key

# poly_key = TRUE
```

# Extra lines in CQ control file

```{r}
# section_extr: vector of strings as CQ command
```

# Item flagging criteria

```{r}
# easy, hard, iRst, fit_w, fit_u, dFallThr, dRiseThr: can change to project requirements
```

