---
title: "equate"
author: "Xiaoliang Zhou"
date: '2022-06-17'
output: html_document
---

# install 'RaschKit' package (if not done yet)

```{r}
# 1. Create a project file 'xxx.Rproj' in a working directory.
# 2. Open 'xxx.Rproj'. From bottom right pane,    
#    click 'Packages' (3rd button after 'Files', 'Plots').
#    click 'Install'. From 'Install from', select 'Package Archive File...'.
#    Click 'Browse'. Enter into 'File name' file path 'T:\Xiaoliang Zhou'.
#    Select compressed file 'RaschKit_1.0.0.tar.gz'. 
#    Click 'Open'. 
#    Click 'Install'.
```

```{r}
library(RaschKit)
install_packages_ls()
create_folders() 
```

```{r}
# 1. move this .Rmd file into the 'rCode' folder just created.
# 2. Put received files into 'dataRaw' folder.
# 3. Open this .Rmd file via 'xxx.Rproj'.
# 4. Select functions proper. Functions
#    would output instructions on where to find report and/or result files.
```

# ###### Dataframe as input

```{r}
Equate(df=df, test='Elana_math', vars=c('NSW', 'VIC'))
# arg 'df': dataframe with cols of 'item','delta.x', error.x','delta.y','error.y'
# .x relates to vars[[1]], .y relates to vars[[2]]
```

# ###### CQ output (.shw) as input

```{r}
Equate_shw(test='elana_math', vars=c('NSW', 'VIC'))
# .shw and other files named as arg 'test' should be in 'output' folder in wd
```

# ###### Horizontal

```{r}
Equate_Hrz(test='R', grades=c(3:6), forms=c('A','B'))
# files whose names cover all combinations of args 'grades' and 'forms' (e.g., R_2A.shw)
# should be in 'output' folder in wd
```

# ###### Vertical

```{r}
Equate_Vrt(test='R', grades=c(2:10))
# files whose names cover all elements of arg 'grades' (e.g., R_2.shw)
# should be in 'output' folder in wd
```
